[tool.poetry]
name = "mujtaba-charm"
version = "0.1.0"
description = ""
authors = ["MujtabaNasir <mujtaba.nasir1312@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.1"
black = "^24.4.2"
isort = "^5.13.2"
coverage = "^7.6.0"
pytest-cov = "^5.0.0"
sphinx = "^7.4.7"
sphinx-autodoc-typehints = "^2.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tools.isort]
profile = "black"
